In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("sales_data_sample.csv",encoding = "latin1")
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [ ]:
df['PRICEEACH'].astype(int)

0        95
1        81
2        94
3        83
4       100
       ...
2818    100
2819    100
2820    100
2821     62
2822     65
Name: PRICEEACH, Length: 2823, dtype: int64

In [ ]:
df.describe()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,QTR_ID,MONTH_ID,YEAR_ID,MSRP
count,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.00000,2823.000000
mean,10258.725115,35.092809,83.658544,6.466171,3553.889072,2.717676,7.092455,2003.81509,100.715551
std,92.085478,9.741443,20.174277,4.225841,1841.865106,1.203878,3.656633,0.69967,40.187912
min,10100.000000,6.000000,26.880000,1.000000,482.130000,1.000000,1.000000,2003.00000,33.000000
25%,10180.000000,27.000000,68.860000,3.000000,2203.430000,2.000000,4.000000,2003.00000,68.000000
50%,10262.000000,35.000000,95.700000,6.000000,3184.800000,3.000000,8.000000,2004.00000,99.000000
75%,10333.500000,43.000000,100.000000,9.000000,4508.000000,4.000000,11.000000,2004.00000,124.000000
max,10425.000000,97.000000,100.000000,18.000000,14082.800000,4.000000,12.000000,2005.00000,214.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   int64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   ORDERDATE         2823 non-null   object
 6   STATUS            2823 non-null   object
 7   QTR_ID            2823 non-null   int64
 8   MONTH_ID          2823 non-null   int64
 9   YEAR_ID           2823 non-null   int64
 10  PRODUCTLINE       2823 non-null   object
 11  MSRP              2823 non-null   int64
 12  PRODUCTCODE       2823 non-null   object
 13  CUSTOMERNAME      2823 non-null   object
 14  PHONE             2823 non-null   object
 15  ADDRESSLINE1      2823 non-null   object
 16  ADDRESSLINE2      302 non-null    object
 17  CITY              2823 non-null   object
 18  STATE             1337 non-null   object
 19  POSTALCODE        2747 non-null   object
 20  COUNTRY           2823 non-null   object
 21  TERRITORY         1749 non-null   object
 22  CONTACTLASTNAME   2823 non-null   object
 23  CONTACTFIRSTNAME  2823 non-null   object
 24  DEALSIZE          2823 non-null   object
dtypes: float64(2), int64(7), object(16)
memory usage: 551.5+ KB

In [ ]:
df.memory_usage()

Index                 132
ORDERNUMBER         22584
QUANTITYORDERED     22584
PRICEEACH           22584
ORDERLINENUMBER     22584
SALES               22584
ORDERDATE           22584
STATUS              22584
QTR_ID              22584
MONTH_ID            22584
YEAR_ID             22584
PRODUCTLINE         22584
MSRP                22584
PRODUCTCODE         22584
CUSTOMERNAME        22584
PHONE               22584
ADDRESSLINE1        22584
ADDRESSLINE2        22584
CITY                22584
STATE               22584
POSTALCODE          22584
COUNTRY             22584
TERRITORY           22584
CONTACTLASTNAME     22584
CONTACTFIRSTNAME    22584
DEALSIZE            22584
dtype: int64

In [ ]:
df.dtypes()

TypeError: 'Series' object is not callable

In [ ]:
df.dtypes

ORDERNUMBER           int64
QUANTITYORDERED       int64
PRICEEACH           float64
ORDERLINENUMBER       int64
SALES               float64
ORDERDATE            object
STATUS               object
QTR_ID                int64
MONTH_ID              int64
YEAR_ID               int64
PRODUCTLINE          object
MSRP                  int64
PRODUCTCODE          object
CUSTOMERNAME         object
PHONE                object
ADDRESSLINE1         object
ADDRESSLINE2         object
CITY                 object
STATE                object
POSTALCODE           object
COUNTRY              object
TERRITORY            object
CONTACTLASTNAME      object
CONTACTFIRSTNAME     object
DEALSIZE             object
dtype: object

In [ ]:
df['COUNTRY'].nunique()

19

In [ ]:
df['STATE'].nunique()

16

In [ ]:
df['COUNTRY'].value_counts()

COUNTRY
USA            1004
Spain           342
France          314
Australia       185
UK              144
Italy           113
Finland          92
Norway           85
Singapore        79
Canada           70
Denmark          63
Germany          62
Sweden           57
Austria          55
Japan            52
Belgium          33
Switzerland      31
Philippines      26
Ireland          16
Name: count, dtype: int64

In [ ]:
print(df.sum(numeric_only = True))

ORDERNUMBER        28960381.00
QUANTITYORDERED       99067.00
PRICEEACH            236168.07
ORDERLINENUMBER       18254.00
SALES              10032628.85
QTR_ID                 7672.00
MONTH_ID              20022.00
YEAR_ID             5656770.00
MSRP                 284320.00
dtype: float64

In [ ]:
print(df.count())

ORDERNUMBER         2823
QUANTITYORDERED     2823
PRICEEACH           2823
ORDERLINENUMBER     2823
SALES               2823
ORDERDATE           2823
STATUS              2823
QTR_ID              2823
MONTH_ID            2823
YEAR_ID             2823
PRODUCTLINE         2823
MSRP                2823
PRODUCTCODE         2823
CUSTOMERNAME        2823
PHONE               2823
ADDRESSLINE1        2823
ADDRESSLINE2         302
CITY                2823
STATE               1337
POSTALCODE          2747
COUNTRY             2823
TERRITORY           1749
CONTACTLASTNAME     2823
CONTACTFIRSTNAME    2823
DEALSIZE            2823
dtype: int64

In [ ]:
print(df['PRICEEACH'].median())

95.7

In [ ]:
print(df.quantile)

<bound method DataFrame.quantile of       ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0           10107               30      95.70                2  2871.00
1           10121               34      81.35                5  2765.90
2           10134               41      94.74                2  3884.34
3           10145               45      83.26                6  3746.70
4           10159               49     100.00               14  5205.27
...           ...              ...        ...              ...      ...
2818        10350               20     100.00               15  2244.40
2819        10373               29     100.00                1  3978.51
2820        10386               43     100.00                4  5417.57
2821        10397               34      62.24                1  2116.16
2822        10414               47      65.52                9  3079.44

            ORDERDATE    STATUS  QTR_ID  MONTH_ID  YEAR_ID  ...  \
0      2/24/2003 0:00   Shipped       1         2     2003  ...
1       5/7/2003 0:00   Shipped       2         5     2003  ...
2       7/1/2003 0:00   Shipped       3         7     2003  ...
3      8/25/2003 0:00   Shipped       3         8     2003  ...
4     10/10/2003 0:00   Shipped       4        10     2003  ...
...               ...       ...     ...       ...      ...  ...
2818   12/2/2004 0:00   Shipped       4        12     2004  ...
2819   1/31/2005 0:00   Shipped       1         1     2005  ...
2820    3/1/2005 0:00  Resolved       1         3     2005  ...
2821   3/28/2005 0:00   Shipped       1         3     2005  ...
2822    5/6/2005 0:00   On Hold       2         5     2005  ...

                       ADDRESSLINE1  ADDRESSLINE2           CITY STATE  \
0           897 Long Airport Avenue           NaN            NYC    NY
1                59 rue de l'Abbaye           NaN          Reims   NaN
2     27 rue du Colonel Pierre Avia           NaN          Paris   NaN
3                78934 Hillside Dr.           NaN       Pasadena    CA
4                   7734 Strong St.           NaN  San Francisco    CA
...                             ...           ...            ...   ...
2818             C/ Moralzarzal, 86           NaN         Madrid   NaN
2819                    Torikatu 38           NaN           Oulu   NaN
2820             C/ Moralzarzal, 86           NaN         Madrid   NaN
2821          1 rue Alsace-Lorraine           NaN       Toulouse   NaN
2822             8616 Spinnaker Dr.           NaN         Boston    MA

     POSTALCODE  COUNTRY TERRITORY CONTACTLASTNAME CONTACTFIRSTNAME DEALSIZE
0         10022      USA       NaN              Yu             Kwai    Small
1         51100   France      EMEA         Henriot             Paul    Small
2         75508   France      EMEA        Da Cunha           Daniel   Medium
3         90003      USA       NaN           Young            Julie   Medium
4           NaN      USA       NaN           Brown            Julie   Medium
...         ...      ...       ...             ...              ...      ...
2818      28034    Spain      EMEA          Freyre            Diego    Small
2819      90110  Finland      EMEA       Koskitalo           Pirkko   Medium
2820      28034    Spain      EMEA          Freyre            Diego   Medium
2821      31000   France      EMEA          Roulet          Annette    Small
2822      51003      USA       NaN         Yoshido             Juri   Medium

[2823 rows x 25 columns]>

In [ ]:
df.quantile([0.25, 0.5, 0.75], numeric_only=True)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,QTR_ID,MONTH_ID,YEAR_ID,MSRP
0.25,10180.0,27.0,68.86,3.0,2203.43,2.0,4.0,2003.0,68.0
0.50,10262.0,35.0,95.70,6.0,3184.80,3.0,8.0,2004.0,99.0
0.75,10333.5,43.0,100.00,9.0,4508.00,4.0,11.0,2004.0,124.0

In [ ]:
df.min(numeric_only=True)

ORDERNUMBER        10100.00
QUANTITYORDERED        6.00
PRICEEACH             26.88
ORDERLINENUMBER        1.00
SALES                482.13
QTR_ID                 1.00
MONTH_ID               1.00
YEAR_ID             2003.00
MSRP                  33.00
dtype: float64

In [ ]:
df.max(numeric_only = True)

ORDERNUMBER        10425.0
QUANTITYORDERED       97.0
PRICEEACH            100.0
ORDERLINENUMBER       18.0
SALES              14082.8
QTR_ID                 4.0
MONTH_ID              12.0
YEAR_ID             2005.0
MSRP                 214.0
dtype: float64

In [ ]:
df.mean(numeric_only=True)

ORDERNUMBER        10258.725115
QUANTITYORDERED       35.092809
PRICEEACH             83.658544
ORDERLINENUMBER        6.466171
SALES               3553.889072
QTR_ID                 2.717676
MONTH_ID               7.092455
YEAR_ID             2003.815090
MSRP                 100.715551
dtype: float64

In [ ]:
df.var(numeric_only =True)

ORDERNUMBER        8.479735e+03
QUANTITYORDERED    9.489571e+01
PRICEEACH          4.070014e+02
ORDERLINENUMBER    1.785773e+01
SALES              3.392467e+06
QTR_ID             1.449322e+00
MONTH_ID           1.337097e+01
YEAR_ID            4.895383e-01
MSRP               1.615068e+03
dtype: float64

In [ ]:
df.std(numeric_only = True)

ORDERNUMBER          92.085478
QUANTITYORDERED       9.741443
PRICEEACH            20.174277
ORDERLINENUMBER       4.225841
SALES              1841.865106
QTR_ID                1.203878
MONTH_ID              3.656633
YEAR_ID               0.699670
MSRP                 40.187912
dtype: float64

In [ ]:
df.apply(lambda row:row["SALES"] - (row["QUANTITYORDERED"]*row["PRICEEACH"]),axis = 1)

0       0.000000e+00
1       4.547474e-13
2       4.547474e-13
3      -4.547474e-13
4       3.052700e+02
            ...
2818    2.444000e+02
2819    1.078510e+03
2820    1.117570e+03
2821    0.000000e+00
2822    4.547474e-13
Length: 2823, dtype: float64

In [ ]:
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [ ]:
df["STATUS"] = df["STATUS"].str.lower()

KeyError: 'STATUS'

In [ ]:
print(df.columns)

AttributeError: 'Series' object has no attribute 'columns'

In [ ]:
df.column()

AttributeError: 'Series' object has no attribute 'column'

In [ ]:
df["STATUS"] = df["STATUS"].str.lower()

In [ ]:
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,on hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [ ]:
import pandas as pd

data = {
    'name': ['Alice Johnson', 'BOB SMITH', 'charlie_brown', 'Diana Prince', 'eve'],
    'email': ['alice@example.com', 'BOB@GMAIL.COM', 'charlie_brown@outlook.com', 'diana.prince@company.com', 'eve@site.org'],
    'job_title': ['Engineer', 'Manager', 'developer', 'CEO', 'intern'],
    'message': ['Hi there!', 'PLEASE CALL ME.', 'Can we meet tomorrow?', 'urgent: need reply', 'ok.']
}

df = pd.DataFrame(data)
print(df)

            name                      email  job_title                message
0  Alice Johnson          alice@example.com   Engineer              Hi there!
1      BOB SMITH              BOB@GMAIL.COM    Manager        PLEASE CALL ME.
2  charlie_brown  charlie_brown@outlook.com  developer  Can we meet tomorrow?
3   Diana Prince   diana.prince@company.com        CEO     urgent: need reply
4            eve               eve@site.org     intern                    ok.

In [ ]:
df['name'].str.lower()

0    alice johnson
1        bob smith
2    charlie_brown
3     diana prince
4              eve
Name: name, dtype: object

In [ ]:
df['job_title'].str.title()

0     Engineer
1      Manager
2    Developer
3          Ceo
4       Intern
Name: job_title, dtype: object

In [ ]:
df['message'].str.count("e")

0    2
1    0
2    3
3    4
4    0
Name: message, dtype: int64

In [ ]:
df["name"].str.get(0)

0    A
1    B
2    c
3    D
4    e
Name: name, dtype: object

In [ ]:
df[df['name']!=df["name"].str.lower()]

            name                     email job_title             message
0  Alice Johnson         alice@example.com  Engineer           Hi there!
1      BOB SMITH             BOB@GMAIL.COM   Manager     PLEASE CALL ME.
3   Diana Prince  diana.prince@company.com       CEO  urgent: need reply

In [ ]:
df['email'].str.len()

0    17
1    13
2    25
3    24
4    12
Name: email, dtype: int64

In [ ]:
df['message'].str.replace("urgent","important")

0                Hi there!
1          PLEASE CALL ME.
2    Can we meet tomorrow?
3    important: need reply
4                      ok.
Name: message, dtype: object

In [ ]:
df['email'].str.slice(0,5)

0    alice
1    BOB@G
2    charl
3    diana
4    eve@s
Name: email, dtype: object

In [ ]:
df['email'].str.partition("@")

               0  1            2
0          alice  @  example.com
1            BOB  @    GMAIL.COM
2  charlie_brown  @  outlook.com
3   diana.prince  @  company.com
4            eve  @     site.org

In [ ]:
df['name'].str.isalnum()

0    False
1    False
2    False
3    False
4     True
Name: name, dtype: bool

In [ ]:
df['job_title'].str.join("-")

0      E-n-g-i-n-e-e-r
1        M-a-n-a-g-e-r
2    d-e-v-e-l-o-p-e-r
3                C-E-O
4          i-n-t-e-r-n
Name: job_title, dtype: object

In [ ]:
import pandas as pd
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': ['4', '5', '6'],  # This is object type
    'C': ['x', 'y', 'z']
})

In [ ]:
df.dtypes

A     int64
B    object
C    object
dtype: object

KeyError: 'B'

In [ ]:
df.dtypes

dtype('int64')

In [ ]:
import pandas as pd
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': ['4', '5', '6'],  # This is object type
    'C': ['x', 'y', 'z']
})


print(df.dtypes)

A     int64
B    object
C    object
dtype: object

In [ ]:
df.convert_dtypes()

   A  B  C
0  1  4  x
1  2  5  y
2  3  6  z

In [ ]:
df

   A  B  C
0  1  4  x
1  2  5  y
2  3  6  z

In [ ]:
df.dtypes

A     int64
B    object
C    object
dtype: object

In [ ]:
import pandas as pd
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': ['4', '5', '6']  # This is object type

})

In [ ]:
df['B'] = pd.to_numeric(df['B'])

In [ ]:
df.dtypes

A    Int64
B    Int64
dtype: object

In [ ]:
import pandas as pd

dates = ['2024-01-01', '2024-02-15', '2024-03-30']
df = pd.to_datetime(dates)

In [ ]:
df.dtype

dtype('<M8[ns]')

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'Name': ['Alice', 'Bob', None],
    'Age': [25, None, 30]
})

# Check for NaN values
print(pd.isna(df))

    Name    Age
0  False  False
1  False   True
2   True  False

In [ ]:
df.isna().sum()

Name    1
Age     1
dtype: int64

In [ ]:
import pandas as pd

# Create sample datetime data
df = pd.DataFrame({
    'event_time': [
        '2024-01-15 10:45:30',
        '2024-03-28 14:22:10',
        '2024-07-04 09:00:00',
        '2024-10-31 18:59:59'
    ]
})

# Convert to datetime type
df['event_time'] = pd.to_datetime(df['event_time'])

In [ ]:
df['event_time'].dt.year_name()

AttributeError: 'DatetimeProperties' object has no attribute 'year_name'

In [ ]:
df['event_time'].dt.month_name()

0    January
1      March
2       July
3    October
Name: event_time, dtype: object

In [ ]:
df['event_time'].dt.day_name()

0      Monday
1    Thursday
2    Thursday
3    Thursday
Name: event_time, dtype: object

In [ ]:
df['event_time'].dt.quarter

0    1
1    1
2    3
3    4
Name: event_time, dtype: int32

In [ ]:
df['event_time'].dt.hour

0    10
1    14
2     9
3    18
Name: event_time, dtype: int32

In [ ]:
df['event_time'].dt.minute

0    45
1    22
2     0
3    59
Name: event_time, dtype: int32

In [ ]:
df['event_time'].dt.second

0    30
1    10
2     0
3    59
Name: event_time, dtype: int32

In [ ]:
df= pd.read_csv("/content/sales_data_sample.csv",encoding = 'latin1')
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [ ]:
df.isna().sum()

ORDERNUMBER            0
QUANTITYORDERED        0
PRICEEACH              0
ORDERLINENUMBER        0
SALES                  0
ORDERDATE              0
STATUS                 0
QTR_ID                 0
MONTH_ID               0
YEAR_ID                0
PRODUCTLINE            0
MSRP                   0
PRODUCTCODE            0
CUSTOMERNAME           0
PHONE                  0
ADDRESSLINE1           0
ADDRESSLINE2        2521
CITY                   0
STATE               1486
POSTALCODE            76
COUNTRY                0
TERRITORY           1074
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
dtype: int64

In [ ]:
df = df.drop(columns=["ADDRESSLINE1", "ADDRESSLINE2", "STATE", "TERRITORY"],axis  = 1)

In [ ]:
df

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,MSRP,PRODUCTCODE,CUSTOMERNAME,PHONE,CITY,POSTALCODE,COUNTRY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,95,S10_1678,Land of Toys Inc.,2125557818,NYC,10022,USA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,95,S10_1678,Reims Collectables,26.47.1555,Reims,51100,France,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,95,S10_1678,Lyon Souveniers,+33 1 46 62 7555,Paris,75508,France,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,95,S10_1678,Toys4GrownUps.com,6265557265,Pasadena,90003,USA,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,95,S10_1678,Corporate Gift Ideas Co.,6505551386,San Francisco,NaN,USA,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,54,S72_3212,Euro Shopping Channel,(91) 555 94 44,Madrid,28034,Spain,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,54,S72_3212,"Oulu Toy Supplies, Inc.",981-443655,Oulu,90110,Finland,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,54,S72_3212,Euro Shopping Channel,(91) 555 94 44,Madrid,28034,Spain,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,54,S72_3212,Alpha Cognac,61.77.6555,Toulouse,31000,France,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,54,S72_3212,Gifts4AllAges.com,6175559555,Boston,51003,USA,Yoshido,Juri,Medium

In [ ]:
df.isna().sum()

ORDERNUMBER          0
QUANTITYORDERED      0
PRICEEACH            0
ORDERLINENUMBER      0
SALES                0
ORDERDATE            0
STATUS               0
QTR_ID               0
MONTH_ID             0
YEAR_ID              0
PRODUCTLINE          0
MSRP                 0
PRODUCTCODE          0
CUSTOMERNAME         0
PHONE                0
CITY                 0
POSTALCODE          76
COUNTRY              0
CONTACTLASTNAME      0
CONTACTFIRSTNAME     0
DEALSIZE             0
dtype: int64

In [ ]:
 mn = df['POSTALCODE'].astype(Int64)
 mn

NameError: name 'Int64' is not defined

In [ ]:
import pandas as pd
df = pd.DataFrame({
    "Age":[10,20,30]
})

In [ ]:
df['Age'].map(lambda x:x*2)

0    20
1    40
2    60
Name: Age, dtype: int64

In [ ]:
df = pd.DataFrame({
    "Num1":[10,20,30],
    "Num2":[40,50,60]
})
df

   Num1  Num2
0    10    40
1    20    50
2    30    60

In [ ]:
df['diff'] = df.apply(lambda x: x['Num2'] - x['Num1'], axis=1)

In [ ]:
df

   Num1  Num2  diff
0    10    40    30
1    20    50    30
2    30    60    30

In [ ]:
len(df)

3

In [ ]:
import pandas as pd
import numpy as np

# Sample Data
df = pd.DataFrame({
    'Length': [10, 20, 30, 40, 50],
    'Height': [5, 4, 6, 3, 2],
    'Depth':  [2, 3, 1, 5, 4],
    'col':    [23, 45, 12, 67, 34]  # For qcut/binning
})

print(df)

   Length  Height  Depth  col
0      10       5      2   23
1      20       4      3   45
2      30       6      1   12
3      40       3      5   67
4      50       2      4   34

In [ ]:
df = df.assign(Area = lambda df:df.Length*df.Height)
df

   Length  Height  Depth  col  Area
0      10       5      2   23    50
1      20       4      3   45    80
2      30       6      1   12   180
3      40       3      5   67   120
4      50       2      4   34   100

In [ ]:
df['volume'] = df.Length*df.Height*df.Depth
df

   Length  Height  Depth  col  Area  volume
0      10       5      2   23    50     100
1      20       4      3   45    80     240
2      30       6      1   12   180     180
3      40       3      5   67   120     600
4      50       2      4   34   100     400

In [ ]:
df['col_bin'] = pd.qcut(df['col'], q=3, labels=False)

In [ ]:
df

   Length  Height  Depth  col  Area  volume  col_bin
0      10       5      2   23    50     100        0
1      20       4      3   45    80     240        2
2      30       6      1   12   180     180        0
3      40       3      5   67   120     600        2
4      50       2      4   34   100     400        1

In [ ]:
df['row_max'] = df[['Length', 'Height', 'Depth']].max(axis=1)

In [ ]:
df

   Length  Height  Depth  col  Area  volume  col_bin  row_max
0      10       5      2   23    50     100        0       10
1      20       4      3   45    80     240        2       20
2      30       6      1   12   180     180        0       30
3      40       3      5   67   120     600        2       40
4      50       2      4   34   100     400        1       50

In [21]:
import pandas as pd

# Sample Data
df = pd.DataFrame({
    'Student': ['Alice', 'Bob', 'Charlie'],
    'Math_2023': [90, 85, 95],
    'Science_2023': [88, 80, 92],
    'Math_2024': [94, 89, 96],
    'Science_2024': [90, 82, 94]
})

print(df)

   Student  Math_2023  Science_2023  Math_2024  Science_2024
0    Alice         90            88         94            90
1      Bob         85            80         89            82
2  Charlie         95            92         96            94

In [22]:
df_melted = pd.melt(df, id_vars='Student', var_name='Subject_Year', value_name='Marks')

In [23]:
df_melted[['Subject','Year']] = df_melted['Subject_Year'].str.split("_",expand = True)

In [27]:
df_pivot = df_melted.pivot(index='Student', columns=['Year','Subject'], values='Marks')

In [28]:
df_pivot

Year    2023         2024
Subject Math Science Math Science
Student
Alice     90      88   94      90
Bob       85      80   89      82
Charlie   95      92   96      94

In [11]:
df1 = df[['Student', 'Math_2023']]
df2 = df[['Student', 'Math_2024']]
df_math = pd.concat([df1, df2], axis=1)  # Append side-by-side (axis=1)

In [12]:
df_math

   Student  Math_2023  Student  Math_2024
0    Alice         90    Alice         94
1      Bob         85      Bob         89
2  Charlie         95  Charlie         96

In [15]:
df_sorted = df.sort_values('Math_2023', ascending=True)

In [16]:
df_sorted

   Student  Math_2023  Science_2023  Math_2024  Science_2024
1      Bob         85            80         89            82
0    Alice         90            88         94            90
2  Charlie         95            92         96            94

In [17]:
df_indexed = df.set_index('Student')

In [18]:
df_indexed

         Math_2023  Science_2023  Math_2024  Science_2024
Student
Alice           90            88         94            90
Bob             85            80         89            82
Charlie         95            92         96            94

In [19]:
df_reset = df_indexed.reset_index()

In [20]:
df_reset

   Student  Math_2023  Science_2023  Math_2024  Science_2024
0    Alice         90            88         94            90
1      Bob         85            80         89            82
2  Charlie         95            92         96            94

In [29]:
import pandas as pd

# Create long-format student data
df = pd.DataFrame({
    'Student': ['Alice', 'Alice', 'Bob', 'Bob', 'Charlie', 'Charlie',
                'Alice', 'Alice', 'Bob', 'Bob', 'Charlie', 'Charlie'],
    'Subject': ['Math', 'Science'] * 6,
    'Year': ['2023'] * 6 + ['2024'] * 6,
    'Marks': [90, 88, 85, 80, 95, 92, 94, 90, 89, 82, 96, 94]
})

In [30]:
df

    Student  Subject  Year  Marks
0     Alice     Math  2023     90
1     Alice  Science  2023     88
2       Bob     Math  2023     85
3       Bob  Science  2023     80
4   Charlie     Math  2023     95
5   Charlie  Science  2023     92
6     Alice     Math  2024     94
7     Alice  Science  2024     90
8       Bob     Math  2024     89
9       Bob  Science  2024     82
10  Charlie     Math  2024     96
11  Charlie  Science  2024     94

In [37]:
grouped = df.groupby(['Student', 'Subject'])

In [38]:
print(grouped.size())

Student  Subject
Alice    Math       2
         Science    2
Bob      Math       2
         Science    2
Charlie  Math       2
         Science    2
dtype: int64

In [40]:
print(grouped.agg(['max','min']))

                 Year       Marks
                  max   min   max min
Student Subject
Alice   Math     2024  2023    94  90
        Science  2024  2023    90  88
Bob     Math     2024  2023    89  85
        Science  2024  2023    82  80
Charlie Math     2024  2023    96  95
        Science  2024  2023    94  92

In [41]:
df['Prev_Marks'] = grouped['Marks'].shift(1)

In [42]:
df

    Student  Subject  Year  Marks  Prev_Marks
0     Alice     Math  2023     90         NaN
1     Alice  Science  2023     88         NaN
2       Bob     Math  2023     85         NaN
3       Bob  Science  2023     80         NaN
4   Charlie     Math  2023     95         NaN
5   Charlie  Science  2023     92         NaN
6     Alice     Math  2024     94        90.0
7     Alice  Science  2024     90        88.0
8       Bob     Math  2024     89        85.0
9       Bob  Science  2024     82        80.0
10  Charlie     Math  2024     96        95.0
11  Charlie  Science  2024     94        92.0

In [43]:
df['Rank_in_Subject'] = df.groupby('Subject')['Marks'].rank(ascending=False, method='dense')

In [44]:
df

    Student  Subject  Year  Marks  Prev_Marks  Rank_in_Subject
0     Alice     Math  2023     90         NaN              4.0
1     Alice  Science  2023     88         NaN              4.0
2       Bob     Math  2023     85         NaN              6.0
3       Bob  Science  2023     80         NaN              6.0
4   Charlie     Math  2023     95         NaN              2.0
5   Charlie  Science  2023     92         NaN              2.0
6     Alice     Math  2024     94        90.0              3.0
7     Alice  Science  2024     90        88.0              3.0
8       Bob     Math  2024     89        85.0              5.0
9       Bob  Science  2024     82        80.0              5.0
10  Charlie     Math  2024     96        95.0              1.0
11  Charlie  Science  2024     94        92.0              1.0

In [48]:
df['Cumulative_Marks'] = grouped['Marks'].cumsum()

In [49]:
df

,Student,Subject,Year,Marks,Prev_Marks,Rank_in_Subject,Cumulative_Marks
0,Alice,Math,2023,90,NaN,4.0,90
1,Alice,Science,2023,88,NaN,4.0,88
2,Bob,Math,2023,85,NaN,6.0,85
3,Bob,Science,2023,80,NaN,6.0,80
4,Charlie,Math,2023,95,NaN,2.0,95
5,Charlie,Science,2023,92,NaN,2.0,92
6,Alice,Math,2024,94,90.0,3.0,184
7,Alice,Science,2024,90,88.0,3.0,178
8,Bob,Math,2024,89,85.0,5.0,174
9,Bob,Science,2024,82,80.0,5.0,162
10,Charlie,Math,2024,96,95.0,1.0,191
11,Charlie,Science,2024,94,92.0,1.0,186

In [50]:
df['CumMax'] = grouped['Marks'].cummax()
df['CumMin'] = grouped['Marks'].cummin()
df['CumProd'] = grouped['Marks'].cumprod()

In [51]:
df

,Student,Subject,Year,Marks,Prev_Marks,Rank_in_Subject,Cumulative_Marks,CumMax,CumMin,CumProd
0,Alice,Math,2023,90,NaN,4.0,90,90,90,90
1,Alice,Science,2023,88,NaN,4.0,88,88,88,88
2,Bob,Math,2023,85,NaN,6.0,85,85,85,85
3,Bob,Science,2023,80,NaN,6.0,80,80,80,80
4,Charlie,Math,2023,95,NaN,2.0,95,95,95,95
5,Charlie,Science,2023,92,NaN,2.0,92,92,92,92
6,Alice,Math,2024,94,90.0,3.0,184,94,90,8460
7,Alice,Science,2024,90,88.0,3.0,178,90,88,7920
8,Bob,Math,2024,89,85.0,5.0,174,89,85,7565
9,Bob,Science,2024,82,80.0,5.0,162,82,80,6560
10,Charlie,Math,2024,96,95.0,1.0,191,96,95,9120
11,Charlie,Science,2024,94,92.0,1.0,186,94,92,8648

In [52]:
import pandas as pd

df = pd.DataFrame({
    'A': [10, 20, 30, 40, 50],
    'B': [5, 4, 3, 2, 1],
    'C': ['x', 'y', 'z', 'x', 'y']
}, index=['r1', 'r2', 'r3', 'r4', 'r5'])

In [53]:
df.loc['r2']

A    20
B     4
C     y
Name: r2, dtype: object

In [54]:
df.loc['r2':'r4']

     A  B  C
r2  20  4  y
r3  30  3  z
r4  40  2  x

In [55]:
df.loc[:,'A']

r1    10
r2    20
r3    30
r4    40
r5    50
Name: A, dtype: int64

In [56]:
df.loc[:,'A':'C']

     A  B  C
r1  10  5  x
r2  20  4  y
r3  30  3  z
r4  40  2  x
r5  50  1  y

In [57]:
df.loc[df['A'] > 20, ['A', 'C']]  # Filter rows & select columns

     A  C
r3  30  z
r4  40  x
r5  50  y